config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  resources :bookmarks

  root 'site#index'

end

app/models/bookmark.rb
class Bookmark < ActiveRecord::Base
  belongs_to :user

  #Ensure user data is present
  validates :user_id, presence: true

  # ensure that title is present and at least 10 chars long
  validates :title, length: {minimum: 10}, presence: true

  # ensure the url is present, and respects the URL format for http/https
  validates :url, format: {with: Regexp.new(URI::regexp(%w(http https)))}, presence: true
end

app/models/user.rb
class User < ActiveRecord::Base
  devise :database_authenticatable, :registerable,
         :rememberable, :validatable

  #Adding accoication for Users to bookmarks
  has_many :bookmarks
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/bookmarks_controller.rb
class BookmarksController < ApplicationController
  # other before_actions
  before_action :set_bookmark, only: [:show, :edit, :update, :destroy]

  #Redirect user to vailidation page before bookmarks
  before_filter :authenticate_user!

  # GET /bookmarks
  # GET /bookmarks.json
  def index
    @bookmarks = Bookmark.all
  end

  # GET /bookmarks/1
  # GET /bookmarks/1.json
  def show
  end

  # GET /bookmarks/new
  def new
    @bookmark = Bookmark.new
  end

  # GET /bookmarks/1/edit
  def edit
  end

  # POST /bookmarks
  # POST /bookmarks.json
  def create
    @bookmark = Bookmark.new(bookmark_params)

    respond_to do |format|
      if @bookmark.save
        format.html { redirect_to @bookmark, notice: 'Bookmark was successfully created.' }
        format.json { render :show, status: :created, location: @bookmark }
      else
        format.html { render :new }
        format.json { render json: @bookmark.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /bookmarks/1
  # PATCH/PUT /bookmarks/1.json
  def update
    respond_to do |format|
      if @bookmark.update(bookmark_params)
        format.html { redirect_to @bookmark, notice: 'Bookmark was successfully updated.' }
        format.json { render :show, status: :ok, location: @bookmark }
      else
        format.html { render :edit }
        format.json { render json: @bookmark.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /bookmarks/1
  # DELETE /bookmarks/1.json
  def destroy
    @bookmark.destroy
    respond_to do |format|
      format.html { redirect_to bookmarks_url, notice: 'Bookmark was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
  # Use callbacks to share common setup or constraints between actions.
  def set_bookmark
    unless @bookmark = current_user.bookmarks.where(id: params[:id]).first
      flash[:alert] = 'Bookmark not found.'
      redirect_to root_url
    end
  end

  # Never trust parameters from the scary internet, only allow the white list through.
  def bookmark_params
    params.require(:bookmark).permit(:title, :url)
  end


end

app/controllers/site_controller.rb
class SiteController < ApplicationController
  def index
    #We are going to return all the books marks in decending order of time created
    @bookmarks = Bookmark.order('created_at desc')
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/bookmarks_helper.rb
module BookmarksHelper
end

app/helpers/site_helper.rb
module SiteHelper
end

app/views/bookmarks/_form.html.erb
<%= simple_form_for(@bookmark) do |f| %>
    <%= f.error_notification %>

    <div class="form-inputs">
      <%= f.input :title %>
      <%= f.input :url %>
    </div>

    <div class="form-actions">
      <%= f.button :submit %>
    </div>
<% end %>

app/views/bookmarks/edit.html.erb
<h1>Editing bookmark</h1>

<%= render 'form' %>

<%= link_to 'Show', @bookmark %> |
<%= link_to 'Back', bookmarks_path %>

app/views/bookmarks/index.html.erb
<h1>Listing bookmarks</h1>

<table>
  <thead>
    <tr>
      <th>Title</th>
      <th>Url</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @bookmarks.each do |bookmark| %>
      <tr>
        <td><%= bookmark.title %></td>
        <td><%= bookmark.url %></td>
        <td><%= link_to 'Show', bookmark %></td>
        <td><%= link_to 'Edit', edit_bookmark_path(bookmark) %></td>
        <td><%= link_to 'Destroy', bookmark, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Bookmark', new_bookmark_path %>

app/views/bookmarks/new.html.erb
<h1>New bookmark</h1>

<%= render 'form' %>

<%= link_to 'Back', bookmarks_path %>

app/views/bookmarks/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Title:</strong>
  <%= @bookmark.title %>
</p>

<p>
  <strong>Url:</strong>
  <%= @bookmark.url %>
</p>

<%= link_to 'Edit', edit_bookmark_path(@bookmark) %> |
<%= link_to 'Back', bookmarks_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<!-- paulirish.com/2008/conditional-stylesheets-vs-css-hacks-answer-neither/ -->
<!--[if lt IE 7 ]> <html class="ie6" lang="en"> <![endif]-->
<!--[if IE 7 ]>    <html class="ie7" lang="en"> <![endif]-->
<!--[if IE 8 ]>    <html class="ie8" lang="en"> <![endif]-->
<!--[if (gte IE 9)|!(IE)]><!--> <html lang="en"> <!--<![endif]-->
<head>
  <meta charset="utf-8" />
  <!-- Uncomment to make IE8 render like IE7 -->
  <!-- <meta http-equiv="X-UA-Compatible" content="IE=7" /> -->

  <!-- Set the viewport width to device width for mobile -->
  <meta name="viewport" content="width=device-width, initial-scale=1.0" />

  <title><%= content_for?(:title) ? yield(:title) : "Bookmarks" %></title>

  <%= stylesheet_link_tag    "application" %>
  <%= javascript_include_tag "vendor/custom.modernizr" %>
  <%= csrf_meta_tags %>
</head>

<body>
<div class="row">
  <div class="large-12 columns">

    <!-- Navigation -->

    <div class="row">
      <div class="large-12 columns">

        <nav class="top-bar">
          <ul class="title-area">
            <!-- Title Area -->
            <li class="name">
              <h1><a href="/">David O'Regan Bookmarks</a></h1>
            </li>
          </ul>

          <section class="top-bar-section">
            <!-- Right Nav Section -->
            <ul class="right">
              <li class="divider"></li>
              <% if current_user %>
                  <li><%= link_to 'My Bookmarks', bookmarks_path %></li>
                  <li class="divider"></li>

                  <li class="has-dropdown">
                    <%= link_to current_user.email, '#'%>
                    <ul class="dropdown">
                      <li><%= link_to 'Profile', edit_user_registration_path %></li>
                      <li><%= link_to 'Logout', destroy_user_session_path, method: :delete %></li>
                      <li class="divider"></li>
                    </ul>
                  </li>
              <% else %>
                  <li><%= link_to 'Login', new_user_session_path %></li>
                  <li><%= link_to 'Register', new_user_registration_path %></li>
              <% end %>
            </ul>
          </section>
        </nav>
        <!-- End Top Bar -->
      </div>
    </div>
    <!-- End Navigation -->

    <!-- Flash messages -->
    <div class="row">
      <div class="large-12 columns">
        <% if flash[:notice] %>
            <div data-alert class="alert-box success">
              <a href="#" class="close">&times;</a>
              <%= flash[:notice] %>
            </div>
        <% end %>

        <% if flash[:alert] %>
            <div data-alert class="alert-box alert">
              <a href="#" class="close">&times;</a>
              <%= flash[:alert] %>
            </div>
        <% end %>
      </div>
    </div>
    <!-- End Flash messages -->

    <!-- Content -->
    <div class="row">
      <div class="large-12 columns">
        <%= yield %>
      </div>
    </div>
    <!-- End Content -->

    <!-- Footer -->
    <footer class="row">
      <div class="large-12 columns"><hr />
        <div class="row">
          <div class="large-6 columns">
            <p>&copy; Copyright no one at all.</p>
          </div>

          <div class="large-6 columns">
            <ul class="inline-list right">
              <li><a href="#">About</a></li>
              <li><a href="#">Twitter</a></li>
              <li><a href="#">Facebook</a></li>
              <li><a href="#">Etc..</a></li>
            </ul>
          </div>
        </div>
      </div>
    </footer>
    <!-- End Footer -->

  </div>
</div>

<%= javascript_include_tag "application" %>
</body>
</html>

app/views/site/index.html.erb
<% if current_user %>
    <h2>Latest Bookmarks</h2>
    <table style="width: 100%">
      <thead>
      <tr>
        <th>Url</th>
      </tr>
      </thead>

      <tbody>
      <% @bookmarks.each do |bookmark| %>
          <tr>
            <td><%= link_to bookmark.title, bookmark.url %></td>
          </tr>
      <% end %>
      </tbody>
    </table>

<% else %>
    <div class="panel">
      <h1>Share your bookmarks!</h1>
      <p>A simple app to track and share your beloved bookmarks with others.</p>
      <%= link_to "Get started today", new_user_registration_path, :class => "button button-large" %>
    </div>
<% end %>